name: Build Docker

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Check Out Repo
                uses: actions/checkout@v3

            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v2

            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v4
                with:
                    push: false
                    tags: oskardudycz/cqrs_is_simpler_with_net:latest

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
